apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudgeeks-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:quickbooks2018/argo-cd.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudgeeks-argocd

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
